micronaut:
  application:
    name: fretesrest

grpc:
  client:
    plaintext: true
    max_retry_attempts: 10
  channels:
    fretes:
      address: 'localhost:50051'
      plaintext: true
      max_retry_attempts: 10
