micronaut:
  application:
    name: carrosGrpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5436/carros_grpc_mk
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
